Added flat-quadrant queue to stampede2 and modified the wrangler template to use the flash

diff --git a/src/scripts/cyverse-sdk-tacc-systems-create b/src/scripts/cyverse-sdk-tacc-systems-create
--- a/src/scripts/cyverse-sdk-tacc-systems-create
+++ b/src/scripts/cyverse-sdk-tacc-systems-create
@@ -124,6 +124,12 @@ WORKD=${WORKD:-$default}
 if [ -z "$WORKD" ]; then echo "Error: TACC work directory can't be left empty."; exit 1; fi
 echo -e "Confirmed: $WORKD"
 
+default=$(echo /gpfs/flash/users/$USERNAME)
+read -p "Wrangler Flash directory [$default]: " FLASHD
+FLASHD=${FLASHD:-$default}
+if [ -z "$FLASHD" ]; then echo "Error: TACC work directory can't be left empty."; exit 1; fi
+echo -e "Confirmed: $FLASHD"
+
 # Register with Agave API
 echo -e "\n*Registering systems with Agave API*"
 TMPDIR="$HOME/tmp"
